### ISSUE TITLE
Story Conversion Fails If Twine Title Contains a Space or Its First Character is a Number

### ISSUE THREAD

**Issue by NovySan** [daterre/Cradle#19]
Publishing to File a Twine 2.0 story (Harlow) called 3 Bug Example or 3BugExample will result in a Story Conversion Fail. BugExample or Bug_Example works fine.

**Comment by daterre** [comment]
Did you get the following error message in the console? This is what you should have seen:
`The story cannot be imported because "3BugExample" is not a valid Unity script name.`

If you did, this is by design. I opted to cancel story conversion rather than automatically sanitize the name because it a script with a different name than the story could be confusing for users.
