### ISSUE TITLE
TwineTextPlayer Formatting Issues

### ISSUE THREAD

**Issue by domportera** [daterre/Cradle#38]
I've been attempting to format story layout using the TwineTextPlayer and I haven't had much luck controlling the positioning and alignment of text. I've tried using all of the alignment controls, and none of them are working as I'd expect them to, except for padding. I also can't seem to get horizontal text overflow to wrap. Oftentimes I mess with the Content Size Fitter, which ends up irreversibly shifting the right border of my text to the far left, forcing me to revert the prefab.

Any idea what I could be doing wrong, or if this is a bug?

I should also mention I'm getting the following warning under the Content Size Fitter script:
"Parent has a type of layout group component. A child of a layout group should not have a Content Size Fitter component, since it should be driven by the layout group."

**Comment by daterre** [comment]
The TwineTextPlayer is really just a demo and not a full fledged Twine-like
player. That is somewhat beyond the scope of this project (which is more
geared towards custom UIs). It hasn't been tested for flexibility or
customization but sort of provided "as-is". It is made with Unity UI though
so anything that framework supports should be possible with it - I suggest
you look at documentation on scrolling elements because that is usually
where the counter-intuitive stuff happens. Sorry I can't be more helpful
than that...

**Comment by domportera** [comment]
Well thanks anyway for the response and a great package nonetheless
