### ISSUE TITLE
Adding stories at runtime (like a mod)?

### ISSUE THREAD

**Issue by fragmental** [daterre/Cradle#70]
I was wondering if there is a way to add twine stories during runtime.  I have seen #66 and I think this is different, but I apologize if this is a duplicate.

What I want to do is build my game once, and then later add the twine story to a folder and have the game automatically detect that story and add it to a list of games to choose from.  I'm thinking something like adding content through the steam workshop or like a wad in doom.  No new build of the game would need to be made, but content could be added and updated separately.

Is something like this possible or feasible with Cradle?

I know how to automatically detect files in a folder and access them, but the files Cradle Generates are C# files, and I've heard that runtime compilation is generally a bad idea.

**Comment by daterre** [comment]
Hi, sorry it took so long to answer. In theory it is possible to compile your Cradle-generated C# story into a DLL which could then be distributed separately and loaded dynamically. I've never tried this with Unity before but it's common practice in .NET/Mono and the API for doing that is right there. However, due to platform limitations this will not work on iOS and other platforms that restrict dynamic code - and definitely won't work with IL2CPP.
